from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .path_builder import (
    NODE_CLASS_MAPPINGS as _PB_CLASSES,
    NODE_DISPLAY_NAME_MAPPINGS as _PB_NAMES,
)

NODE_CLASS_MAPPINGS.update(_PB_CLASSES)
NODE_DISPLAY_NAME_MAPPINGS.update(_PB_NAMES)

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
